################################################################################
############################ Variables to change ###############################
##### Sources directory.
SRC_DIR            = src/

##### Resources directory. It allows you to put all your resources in a single
##### directory and you can include your files using the related path from this
##### directory.
RES_DIR            = res/

##### Theme directory. If you use a personalized theme, you can put all files in this directory.
THEME_DIR          = theme/

##### Bibliography directory. Contains all bib files.
BIB_DIR            = bib/

##### Main file, without .tex extension.
NAME               = main

##### Output directory (without / at the end).
# If not modified, it is the directory which holds the MakeFile.
OUTPUT_DIR         = build/

##### Directory you can put any other external tex files
LIB_DIR            = lib/
##### Executable/output to use: PDFLATEX, DVILUATEX
CC                 = $(PDFLATEX)
CC_BIB             = $(BIBTEX)
USE_BIB            = true
################################################################################